name: Github Action 

on: [push]
 
jobs:
  my-first-job:
    runs-on: ubuntu-latest

    steps:
      - name: hello
        run: |
          echo " This is second time using ci/cd but this time as a ML engineer"
