wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.10
    cli_version: 0.15.8
    is_jupyter_run: true
    is_kaggle_kernel: true
    start_time: 1692115435.86283
    t:
      1:
      - 55
      - 105
      2:
      - 55
      - 105
      3:
      - 2
      - 23
      4: 3.10.10
      5: 0.15.8
      8:
      - 1
      - 2
      - 4
      - 5
